### ISSUE TITLE
KeyError: 'region_eu868' Packet Forwarder crashing

### ISSUE THREAD

**Issue by KevinWassermann94** [NebraLtd/hm-pktfwd#68]
10.11.21 15:24:59 (+0100)  packet-forwarder  Starting
10.11.21 15:25:01 (+0100)  packet-forwarder  SX1301
10.11.21 15:25:01 (+0100)  packet-forwarder  Frequency region_eu868
10.11.21 15:25:02 (+0100)  packet-forwarder  Traceback (most recent call last):
10.11.21 15:25:02 (+0100)  packet-forwarder    File "configurePktFwd.py", line 151, in <module>
10.11.21 15:25:02 (+0100)  packet-forwarder      writeRegionConfSx1301(regionID)
10.11.21 15:25:02 (+0100)  packet-forwarder    File "configurePktFwd.py", line 99, in writeRegionConfSx1301
10.11.21 15:25:02 (+0100)  packet-forwarder      regionconfFile = "/opt/iotloragateway/packet_forwarder/sx1301/lora_templates_sx1301/"+regionList[regionId]
10.11.21 15:25:02 (+0100)  packet-forwarder  KeyError: 'region_eu868'

Happening on https://dashboard.balena-cloud.com/devices/33e2f8d0d955afe3f46c7d6ae6a3bd9c/summary and
https://dashboard.balena-cloud.com/devices/cedf46b90d401a31fc86a7eea99d874a/summary

**Comment by KevinWassermann94** [comment]
closed by #199
